### ISSUE TITLE
HTTP CORS?

### ISSUE THREAD

**Issue by danielweck** [iherman/respec2epub#24]
Hello Ivan,
first of all: cool project :)

I was playing with the demo site:
https://labs.w3.org/epub-generator/
...using this Respec URL:
http://w3c.github.io/dpub-accessibility/
(works great)

The HTTP GET URL works fine too:
https://labs.w3.org/epub-generator/cgi-bin/epub-generator.py?type=html&url=http%3A%2F%2Fw3c.github.io%2Fdpub-accessibility
...but unfortunately there are no CORS headers included in the HTTP response, so I cannot fetch the `application/epub+zip` payload from a web browser (that is to say, from `XmlHttpRequest`).

Here's the list of HTTP headers returned by a `curl` HEAD request:

`$ curl --head "https://labs.w3.org/epub-generator/cgi-bin/epub-generator.py?type=html&url=http%3A%2F%2Fw3c.github.io%2Fdpub-accessibility"`

```
HTTP/1.1 200 OK
Date: Thu, 10 Mar 2016 16:05:00 GMT
Server: Apache/2.2.22 (Debian)
Expires: Thu, 10 Mar 2016 16:05:00 GMT
Content-Disposition: attachment; filename=index.epub
Last-Modified: Thu, 10 Mar 2016 16:05:00 GMT
Content-Length: 145203
Content-Type: application/epub+zip
Strict-Transport-Security: max-age=15552015; preload
Public-Key-Pins: pin-sha256="cN0QSpPIkuwpT6iP2YjEo1bEwGpH/yiUn6yhdy+HNto="; pin-sha256="WGJkyYjx1QMdMe0UqlyOKXtydPDVrk7sl2fV+nNm1r4="; pin-sha256="LrKdTxZLRTvyHM4/atX2nquX9BeHRZMCxg3cf4rhc2I="; max-age=864000
```

So, I tried using a CORS proxy, unfortunately to no avail:
https://crossorigin.me/https://labs.w3.org/epub-generator/cgi-bin/epub-generator.py?type=html&url=http%3A%2F%2Fw3c.github.io%2Fdpub-accessibility

`$ curl --head "https://crossorigin.me/https://labs.w3.org/epub-generator/cgi-bin/epub-generator.py?type=html&url=http%3A%2F%2Fw3c.github.io%2Fdpub-accessibility"`

```
HTTP/2.0 500
server:cloudflare-nginx
date:Thu, 10 Mar 2016 16:07:56 GMT
content-type:text/html; charset=iso-8859-1
set-cookie:__cfduid=d2232775d992c99ef835d9fcfc48f8dd61457626075; expires=Fri, 10-Mar-17 16:07:55 GMT; path=/; domain=.crossorigin.me; HttpOnly
access-control-allow-origin:*
access-control-allow-credentials:false
access-control-allow-headers:Content-Type
expires:Fri, 11 Mar 2016 16:07:55 GMT
cf-ray:281805be638334fa-LHR
```

There are alternative CORS proxies, such as:

http://cors.io/?u=https%3A%2F%2Flabs.w3.org%2Fepub-generator%2Fcgi-bin%2Fepub-generator.py%3Ftype%3Dhtml%26url%3Dhttp%253A%252F%252Fw3c.github.io%252Fdpub-accessibility
...but unfortunately in this case the response content-type is incorrect.

So ideally, could https://labs.w3.org/epub-generator/cgi-bin/epub-generator.py itself be updated to emit CORS headers?

PS: I am just toying with the idea of using Readium to read ReSpec EPUBs directly from your HTTP URLs :)

Thanks!

**Comment by iherman** [comment]
Daniel,

> On 10 Mar 2016, at 17:23, Daniel Weck notifications@github.com wrote:
> 
> Hello Ivan,
> first of all: cool project :)

Thanks :-)

> I was playing with the demo site:
> https://labs.w3.org/epub-generator/ https://labs.w3.org/epub-generator/
> ...using this Respec URL:
> http://w3c.github.io/dpub-accessibility/ http://w3c.github.io/dpub-accessibility/
> (works great)
> 
> The HTTP GET URL works fine too:
> https://labs.w3.org/epub-generator/cgi-bin/epub-generator.py?type=html&url=http%3A%2F%2Fw3c.github.io%2Fdpub-accessibility https://labs.w3.org/epub-generator/cgi-bin/epub-generator.py?type=html&url=http%3A%2F%2Fw3c.github.io%2Fdpub-accessibility
> ...but unfortunately there are no CORS headers included in the HTTP response, so I cannot fetch the application/epub+zip payload from a web browser (that is to say, from XmlHttpRequest).

I am not sure what you mean. If I use that URL above in my browser, then the content is downloaded on my disc without any further ado. What is exactly what you want to achieve?

Ivan

> Here's the list of HTTP headers returned by a curl HEAD request:
> 
> $ curl --head "https://labs.w3.org/epub-generator/cgi-bin/epub-generator.py?type=html&url=http%3A%2F%2Fw3c.github.io%2Fdpub-accessibility"
> 
> HTTP/1.1 200 OK
> Date: Thu, 10 Mar 2016 16:05:00 GMT
> Server: Apache/2.2.22 (Debian)
> Expires: Thu, 10 Mar 2016 16:05:00 GMT
> Content-Disposition: attachment; filename=index.epub
> Last-Modified: Thu, 10 Mar 2016 16:05:00 GMT
> Content-Length: 145203
> Content-Type: application/epub+zip
> Strict-Transport-Security: max-age=15552015; preload
> Public-Key-Pins: pin-sha256="cN0QSpPIkuwpT6iP2YjEo1bEwGpH/yiUn6yhdy+HNto="; pin-sha256="WGJkyYjx1QMdMe0UqlyOKXtydPDVrk7sl2fV+nNm1r4="; pin-sha256="LrKdTxZLRTvyHM4/atX2nquX9BeHRZMCxg3cf4rhc2I="; max-age=864000
> So, I tried using a CORS proxy, unfortunately to no avail:
> https://crossorigin.me/https://labs.w3.org/epub-generator/cgi-bin/epub-generator.py?type=html&url=http%3A%2F%2Fw3c.github.io%2Fdpub-accessibility https://crossorigin.me/https://labs.w3.org/epub-generator/cgi-bin/epub-generator.py?type=html&url=http%3A%2F%2Fw3c.github.io%2Fdpub-accessibility
> $ curl --head "https://crossorigin.me/https://labs.w3.org/epub-generator/cgi-bin/epub-generator.py?type=html&url=http%3A%2F%2Fw3c.github.io%2Fdpub-accessibility"
> 
> HTTP/2.0 500
> server:cloudflare-nginx
> date:Thu, 10 Mar 2016 16:07:56 GMT
> content-type:text/html; charset=iso-8859-1
> set-cookie:__cfduid=d2232775d992c99ef835d9fcfc48f8dd61457626075; expires=Fri, 10-Mar-17 16:07:55 GMT; path=/; domain=.crossorigin.me; HttpOnly
> access-control-allow-origin:*
> access-control-allow-credentials:false
> access-control-allow-headers:Content-Type
> expires:Fri, 11 Mar 2016 16:07:55 GMT
> cf-ray:281805be638334fa-LHR
> There are alternative CORS proxies, such as:
> 
> http://cors.io/?u=https%3A%2F%2Flabs.w3.org%2Fepub-generator%2Fcgi-bin%2Fepub-generator.py%3Ftype%3Dhtml%26url%3Dhttp%253A%252F%252Fw3c.github.io%252Fdpub-accessibility http://cors.io/?u=https%3A%2F%2Flabs.w3.org%2Fepub-generator%2Fcgi-bin%2Fepub-generator.py%3Ftype%3Dhtml%26url%3Dhttp%253A%252F%252Fw3c.github.io%252Fdpub-accessibility
> ...but unfortunately in this case the response content-type is incorrect.
> 
> So ideally, could https://labs.w3.org/epub-generator/cgi-bin/epub-generator.py https://labs.w3.org/epub-generator/cgi-bin/epub-generator.py itself be updated to emit CORS headers?
> 
> PS: I am just toying with the idea of using Readium to read ReSpec EPUBs directly from your HTTP URLs :)
> 
> Thanks!
> 
> —
> Reply to this email directly or view it on GitHub https://github.com/iherman/respec2epub/issues/24.

---

Ivan Herman
Bankrashof 108
1183NW Amstelveen, The Netherlands
http://www.ivan-herman.net

**Comment by danielweck** [comment]
I would like to be able to use XmlHttpRequest from Javascript in a web browser so that my app (arbitrary domain) can fetch the EPUB payload returned by your cgi-bin URL (different origin).

**Comment by iherman** [comment]
Ah! I have no idea what I can/should do, but only tomorrow. In fact, the service has not been planned to be used this way, but from within respec.

Actually... when I use it from respec, it means that the respec javascript calls out to that URI, and I have not had any problems...

TBD:-)

Ivan

**Comment by iherman** [comment]
Daniel,

I have to witness here my complete ignorance of CORS' details (something that I should take care of…). But I know what I have to do, ie, where I have to add those extra entries in my code. Can you tell me which extra headers I should put into the response header?

I could try to understand the CORS spec, but it would take a lot of time and, in the meantime, I am sure I would do something stupid…

**Comment by danielweck** [comment]
With Apache `.htaccess`, you could try something like:

```
<ifModule mod_headers.c>

Header set Access-Control-Allow-Origin "*"

Header set Access-Control-Allow-Credentials "true"

Header set Access-Control-Allow-Methods "GET, HEAD"

Header set Access-Control-Allow-Headers "Range, Content-Type, Origin, X-Requested-With, Accept, Accept-Language, Content-Language"

Header set Access-Control-Expose-Headers "Accept-Ranges, Content-Encoding, Content-Type, Content-Length, Content-Range, Content-Language, Cache-Control, Expires, Last-Modified, Pragma"

</ifModule>
```

Additional configuration directive to ensure no messing-up with zipped EPUB loading:

```
SetEnv no-gzip 1
<ifModule mod_gzip.c>
  mod_gzip_on No
</ifModule>
```

**Comment by danielweck** [comment]
With Amazon AWS S3, something like this:

```
<?xml version="1.0" encoding="UTF-8"?>
<CORSConfiguration xmlns="http://s3.amazonaws.com/doc/2006-03-01/">
    <CORSRule>
        <AllowedOrigin>*</AllowedOrigin>
        <AllowedMethod>GET</AllowedMethod>
        <AllowedMethod>HEAD</AllowedMethod>
        <AllowedHeader>*</AllowedHeader>
        <ExposeHeader>Accept-Ranges</ExposeHeader>
        <ExposeHeader>Content-Range</ExposeHeader>
        <ExposeHeader>Content-Encoding</ExposeHeader>
        <ExposeHeader>Content-Length</ExposeHeader> 
    </CORSRule>
</CORSConfiguration>
```

**Comment by danielweck** [comment]
Also make sure to respond with the content-type `application/epub+zip`, not `application/octet-stream` (just a thought, as I have not checked your HTTP headers)

**Comment by iherman** [comment]
O.k. I do not do this with .htaccess (I do not think I have the possibility to add .htaccess at that particular place), but the headers are generated from my python file, so I will add these in the code. B.t.w., I already return epub as a content type.

But… that will be for tomorrow:-)

**Comment by iherman** [comment]
@danielweck can you try again?

**Comment by danielweck** [comment]
The new CORS headers work fine :) Thanks!

Example Readium URL:

https://readium.firebaseapp.com/?epub=https%3A%2F%2Flabs.w3.org%2Fepub-generator%2Fcgi-bin%2Fepub-generator.py%3Ftype%3Dhtml%26url%3Dhttp%253A%252F%252Fw3c.github.io%252Fdpub-accessibility

The authored hyperlinks in the ReSpec example above don't work in Readium right now. That's because the document data is fetched directly from a zipped EPUB with a weird URL format (it's an edge-case bug that could be fixed in Readium though). Exploded EPUBs do not exhibit this type of problem, because they have resource URLs that can be resolved via HTTP responses without any level of indirection. Anyway, you might see this error when clicking on links:

```
Epub Generator Exception

Traceback (most recent call last):
  File "/home/ivan/htdocs/cgi-bin/epub-generator.py", line 189, in 
    Generator().process()
  File "/home/ivan/htdocs/cgi-bin/epub-generator.py", line 175, in process
    wrapper = self.generate_ebook()
  File "/home/ivan/htdocs/cgi-bin/epub-generator.py", line 163, in generate_ebook
    logger=logger
  File "/home/ivan/lib/python/rp2epub/doc2epub.py", line 70, in __init__
    base_path  = url_tuples.path if url_tuples.path[-1] == '/' else url_tuples.path.rsplit('/', 1)[0] + '/'
IndexError: string index out of range
```

**Comment by iherman** [comment]
> On 16 Mar 2016, at 18:11, Daniel Weck notifications@github.com wrote:
> 
> The new CORS headers work fine :) Thanks!
> 
> Example Readium URL:
> 
> https://readium.firebaseapp.com/?epub=https%3A%2F%2Flabs.w3.org%2Fepub-generator%2Fcgi-bin%2Fepub-generator.py%3Ftype%3Dhtml%26url%3Dhttp%253A%252F%252Fw3c.github.io%252Fdpub-accessibility https://readium.firebaseapp.com/?epub=https%3A%2F%2Flabs.w3.org%2Fepub-generator%2Fcgi-bin%2Fepub-generator.py%3Ftype%3Dhtml%26url%3Dhttp%253A%252F%252Fw3c.github.io%252Fdpub-accessibility
> The authored hyperlinks in the ReSpec example above don't work in Readium right now. That's because the document data is fetched directly from a zipped EPUB with a weird URL format (it's an edge-case bug that could be fixed in Readium though). Exploded EPUBs do not exhibit this type of problem, because they have resource URLs that can be resolved via HTTP responses without any level of indirection. Anyway, you might see this error when clicking on links:
> 
> Epub Generator Exception
> 
> Traceback (most recent call last):
>   File "/home/ivan/htdocs/cgi-bin/epub-generator.py", line 189, in 
>     Generator().process()
>   File "/home/ivan/htdocs/cgi-bin/epub-generator.py", line 175, in process
>     wrapper = self.generate_ebook()
>   File "/home/ivan/htdocs/cgi-bin/epub-generator.py", line 163, in generate_ebook
>     logger=logger
>   File "/home/ivan/lib/python/rp2epub/doc2epub.py", line 70, in **init**
>     base_path  = url_tuples.path if url_tuples.path[-1] == '/' else url_tuples.path.rsplit('/', 1)[0] + '/'
> IndexError: string index out of range
> Yeah… apart from generating a more decent error message instead of relying on the Python default exception, I am not sure what one would do. The program relies on the fact that the data is provided as a URL, which is either of the form http://www.ex.org/a/b/ http://www.ex.org/a/b/ or http://www.ex.org/a/b http://www.ex.org/a/b and that it can derive a "base URL" that can be used when handling other resources (everything that can be expressed in relative URI-s should be also dowloaded in the book). It may not be fool proof, but the goal of the program was, fundamentally, to work with respec, where this issue is not a problem.

Ie, I am afraid fully handling that would go beyond what the original goal was:-(

**Comment by danielweck** [comment]
It's a bug in Readium, you don't have to worry about it :)
