### ISSUE TITLE
Cannot generate EPUB for a ReSpec document

### ISSUE THREAD

**Issue by xfq** [iherman/respec2epub#30]
I was trying to export an EPUB version of https://w3c.github.io/jlreq/ , but got the following error:

```
Traceback (most recent call last):
  File "/home/ivan/htdocs/cgi-bin/epub-generator.py", line 189, in 
    Generator().process()
  File "/home/ivan/htdocs/cgi-bin/epub-generator.py", line 175, in process
    wrapper = self.generate_ebook()
  File "/home/ivan/htdocs/cgi-bin/epub-generator.py", line 163, in generate_ebook
    logger=logger
  File "/home/ivan/lib/python/rp2epub/doc2epub.py", line 84, in __init__
    session = HttpSession(CONVERTER + url if is_respec else url, raise_exception=True, is_respec=is_respec)
  File "/home/ivan/lib/python/rp2epub/utils.py", line 514, in __init__
    handle_exception("There seems to be a problem with the spec generator service ('%s' should be tested separately)" % url)
  File "/home/ivan/lib/python/rp2epub/utils.py", line 502, in handle_exception
    raise R2EError(message)
R2EError: "There seems to be a problem with the spec generator service ('https://labs.w3.org/spec-generator/?type=respec&url=https://w3c.github.io/jlreq/' should be tested separately)"
```

See https://labs.w3.org/epub-generator/cgi-bin/epub-generator.py?type=respec&url=https%3A%2F%2Fw3c.github.io%2Fjlreq%2F for the error.

I'm not sure it is an issue of [spec generator](https://github.com/w3c/spec-generator) or [epub generator](https://labs.w3.org/epub-generator/), so filing an issue here first.

**Comment by iherman** [comment]
Well... The error message says that it is a problem respec2epub experienced running the spec generator... Have you tried to run it separately?

**Comment by iherman** [comment]
B.t.w., I am happy somebody does use this generator. If there are indeed users out there, I might look at the package again.I see two problems coming up with it:

- it has been written in Python2 and not Python3, and the former is going out of usage. It is a non-trivial exercise to convert this to Python3 (in spite of what the python people say; I have had some bad experience with some bigger projects)
- the EPUB3 output is probably not 100% o.k. with the latest EPUB checkers, and the package should be revised.
- there were some (ugly) tricks done in the past to adjust to the peculiarities of particular reading systems (e.g., Apple Books). I would have to test whether they are still relevant.

I am playing with the idea of re-writing the whole thing from scratch. If I do that, I would

- Write it in Typescript with an easier integration with respec (@marcoscaceres, is that a fair assumption?)
- The current version was done in the middle of the transition of the TR styles from the old style to the new one devised by Fantasai & Co. This has added some extra complications to the code, which may be dumped now

But this is a major undertaking, so it may take some time (if ever...)

**Comment by marcoscaceres** [comment]
> Write it in Typescript with an easier integration with respec (@marcoscaceres, is that a fair assumption?)

Indeed it is. But I think the core question is if anyone is using it? If not, we should maybe consider retiring it.

**Comment by iherman** [comment]
Well, this issue started because somebody else is using it:-) And, of course, I do. Creating an EPUB version of the spec is still the best offlining option, in my view, if you want to result to be available on your various devices. (I also find the user interface of most of the epub readers way better for such long reading then what browsers provide, but tastes differ.) I would definitely not be happy retiring it.

@marcoscaceres if I do this, my usual way of operation these days is to set up a node.js+npm+typescript 'project', starting with the HTML file generated by respec (or maybe the XHTML, I still have to decide). Anything special I have to consider to make a possible future integration easier? (I have not looked at respec for a fairly long time and I am not familiar with the way the package operates...)

**Comment by marcoscaceres** [comment]
It should be pretty easy. As you said, ReSpec can give you the generated HTML, and then we just add the metadata and zip it all up. Generating the metadata is probably the hardest bit.

**Comment by iherman** [comment]
Yeah, it has some complications...

- I have to collect all files that should be in the zip files, including, for example, the CSS files that are on the W3C site (but not in the document's directories). Which also means that the relevant references must be found. 
- The experience with some reading systems is that some extra css stuff has to be added (I vaguely remember that Apple's iBooks needed some extra margins for the core CSS to work properly). Awful, I know, but necessary
- The EPUB3 usage of Zip is a big peculiar; there is a file that must be 'on top' of the archive and not compressed. I am not sure all zip packages give me this type of flexibility
- As you say, metadata has to be collected but, actually, that is the easier part:-)

To be seen.

**Comment by iherman** [comment]
> It should be pretty easy. As you said, ReSpec can give you the generated HTML, and then we just add the metadata and zip it all up. Generating the metadata is probably the hardest bit.

Hey @marcoscaceres, in the meantime, I did re-implemented all this in Typescript, see [r2epub](https://github.com/iherman/r2epub). There is also a service doing the job on heroku; I intend to send a PR for respec to use the new (and maintained) service. (I just have to see with our system guys whether they prefer to run the service on w3c lab.)

Although I did "browserify" the code, so it can also run in a client, I think it would be too heavy (and more complicated) to be incorporated into the client-side respec code (I am not familiar with the tools that you guys use to package up the whole code into a client-side script, for example). WDYT?

As I said in https://github.com/iherman/respec2epub/issues/30#issuecomment-587436293, it was a bit more complicated than what you describe above (if you are interested, some of the steps are described in the [documentation](https://iherman.github.io/r2epub/typedoc/classes/_lib_convert_.respectoepub.html), but it was a good learning exercise for me:-). The result is now fully valid with the latest version of [epubcheck](https://github.com/w3c/epubcheck), too.

**Comment by marcoscaceres** [comment]
cc @sidvishnoi for thoughts... 

> Although I did "browserify" the code, so it can also run in a client, I think it would be too heavy (and more complicated) to be incorporated into the client-side respec code (I am not familiar with the tools that you guys use to package up the whole code into a client-side script, for example). WDYT?

If we can run things on the server, that's better for us. Then we can just request the output from ReSpec as we do today. 

Another solution is to add this to the ReSpec Builder (node application)... then we don't need two CLI applications... then we could just have a `--format=epub` and it would just work. We wouldn't need to bundle r2epub into the JS library - we would just add it to the command line tool.

**Comment by sidvishnoi** [comment]
+1 Running on the server is better for us as well as for the users, as it'll be much lighter. We can still send http request from ReSpec Builder, so CLI isn't necessary - but good to have.

**Comment by iherman** [comment]
> +1 Running on the server is better for us as well as for the users, as it'll be much lighter.

Ok. As I said, I will have to see with W3C whether I would move the server there; the version on hedoku is already operational. I will then provide a (trivial) PR.

**Comment by iherman** [comment]
@sidvishnoi for some reasons I could not create a PR from https://github.com/iherman/respec (the system did not allow me to do so). The only change needed is in the file src/ui/save-html.js; lines 28-35 shoud now say:

```js
// Create and download an EPUB 3.2 version of the content
// Using the EPUB 3.2 conversion service set up at labs.w3.org/r2epub
// For more details on that service, see https://github.com/iherman/respec2epub
const epubURL = new URL(
  "https://labs.w3.org/r2epub/"
);
epubURL.searchParams.append("respec", "true");
epubURL.searchParams.append("url", document.location.href);
```

see also https://github.com/iherman/respec/blob/gh-pages/src/ui/save-html.js.

@marcoscaceres

**Comment by iherman** [comment]
Closing by virtue of https://github.com/w3c/respec/pull/2965
